# Generated by Django 4.1.3 on 2022-11-28 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
