# Generated by Django 4.1.3 on 2022-11-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='verify_handle', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
